<script setup lang="ts">
    import { computed } from 'vue';
    import { useRoute } from 'vue-router';
    import { useAuth, hasRole } from '@/composables/auth';
    import { useProfileColor } from '@/composables/profileColor';
    import router from '@/router';

    const route = useRoute();
    const currentRoute = computed(() => route.path);
    const { user, logout } = useAuth();
    const profileColor = useProfileColor();

    const initials = computed(() => {
        if (!user.value) return '';
        return user.value.username
            .split(' ')
            .map(w => w[0])
            .join('')
            .toUpperCase()
            .slice(0, 2);
    });

    const avatarStyle = computed(() => {
        return { background: profileColor.value };
    });

    async function handleLogout() {
        router.push('/')
        await logout();
    }
</script>

<template>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" @click="$router.push('/')">
                <img src="../assets/logo_ai.webp" alt="Bootstrap" height="50">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" :class="{ active: currentRoute === '/' }" @click="$router.push('/')">Etusivu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" :class="{ active: currentRoute === '/about' }" @click="$router.push('/about')">Lisätietoja</a>
                    </li>
                    <li v-if="!user" class="nav-item">
                        <a class="nav-link" :class="{ active: currentRoute === '/signup' }" @click="$router.push('/signup')">Rekisteröidy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" :class="{ active: currentRoute === '/contact' }" @click="$router.push('/contact')">Ota yhteyttä</a>
                    </li>
                </ul>
                <ul v-if="user" class="navbar-nav ms-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle profile-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="avatar" :style="avatarStyle">{{ initials }}</span>
                            <span class="username">{{ user.username }}</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end dropdown-dark">
                            <li><span class="dropdown-text">{{ user.email }}</span></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a v-if="hasRole('Admin')" class="dropdown-item" :class="{ active: currentRoute === '/admin' }" href="#" @click.prevent="$router.push('/admin')">Admin</a></li>
                            <li><a class="dropdown-item" :class="{ active: currentRoute === '/account' }" href="#" @click.prevent="$router.push('/account')">Tiliasetukset</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#" @click.prevent="handleLogout">Kirjaudu ulos</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<style scoped>
    .navbar {
        background-color: rgba(5, 5, 8, 0.9) !important;
        border-bottom: 1px solid #1a1a2a;
    }

    .navbar-brand {
        color: #ffffff !important;
    }

    .navbar-brand img {
        border-radius: 10px;
        cursor: pointer;
    }

    .navbar-toggler {
        border-color: #1a1a2a !important;
    }

    .navbar-toggler-icon {
        /* Made by AI */
        background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba(255, 255, 255, 0.8)' stroke-linecap='round' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e") !important;
    }

    .nav-link {
        cursor: pointer;
        color: #8a8a9a !important;
        transition: color 0.2s, font-weight 0.2s;
    }

    .nav-link:hover,
    .nav-link:focus {
        color: #ffffff !important;
    }

    .nav-link.active,
    .dropdown-item.active {
        color: #00e5ff !important;
        font-weight: 700;
    }

    /* Profile avatar */
    .profile-link {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        padding-right: 0.75rem !important;
    }

    /* Generated by AI */
    .avatar {
        width: 32px;
        height: 32px;
        border-radius: 50%;
        background: #00e5ff;
        color: #000;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        font-weight: 700;
        font-size: 0.8rem;
        flex-shrink: 0;
    }

    .username {
        color: #ffffff !important;
        font-weight: 600;
    }

    .dropdown-dark {
        background: #0d0d14 !important;
        border-color: #1a1a2a !important;
        min-width: 180px;
    }

    .dropdown-dark .dropdown-text {
        color: #8a8a9a;
        padding: 0.5rem 1rem;
        font-size: 0.85rem;
    }

    .dropdown-dark .dropdown-item {
        color: #ffffff !important;
    }

    .dropdown-dark .dropdown-item:hover {
        background: #1a1a2a !important;
        color: #00e5ff !important;
    }

    .dropdown-dark .dropdown-divider {
        border-top-color: #1a1a2a;
    }
</style>
